### ISSUE TITLE
Permission and Usage of Prompts for Raycast Extension

### ISSUE THREAD

**Issue by escwxyz** [pontusab/cursor.directory#50]
Hello,

I'm writing this issue regarding my recent development of a Raycast extension named "cursor-directory", which ported functionalities from your project. I greatly appreciate your work and think that the integration could be beneficial to both our users. However, before proceeding with using the prompts provided by your project, I would like to clarify certain aspects concerning licensing.

The repository for my project is available here: [cursor-directory Raycast Extension](https://github.com/escwxyz/cursor-directory).

Since the license is not explicitly stated in your project's repository, I believe it's prudent to seek permission regarding the use of prompts. 

If you do not have any objections, I would like to proceed with using the prompts provided by your project for my Raycast extension. My intention is to publish this extension on the Raycast store and continue improving it based on the evolving of cursor.directory and user feedback.

Thank you for considering this request.

**Comment by pontusab** [comment]
awesome, do it!

**Comment by escwxyz** [comment]
Thanks for your confirmation.

I am closing this for now.

**Comment by escwxyz** [comment]
https://www.raycast.com/escwxyz/cursor-directory 

it is up

**Comment by pontusab** [comment]
100% awesome! https://x.com/pontusab/status/1833518078359179620

**Comment by escwxyz** [comment]
https://github.com/raycast/extensions/pull/14457

API adoption, many minor fixes and improvements are coming.

**Comment by escwxyz** [comment]
> [raycast/extensions#14457](https://github.com/raycast/extensions/pull/14457)
> 
> API adoption, many minor fixes and improvements are coming.

PR merged!
